### ISSUE TITLE
Fehler bei Profession Henker

### ISSUE THREAD

**Issue by GaeTob80** [gizmo2342/foundryvtt-hexxen1733-system#17]
Bei der Profession Henker ist ein Fehler in der Ausbaukraft.

Es sind die Ausbaukräfte Medizin und Schwarzmarkt doppelt vorhanden, dafür fehlt die Ausbaukraft Kunstobjekte in der Gesellenreihe sowie Talismane in der Expertenreihe.

**Comment by evilblubb** [comment]
Oh stimmt, hab da nen fehler beim Übertragen gemacht (man sollte nicht alles in einer Nacht durchdrücken) - wollte zwischen den Jahren schauen was noch fehlt - werde dabei Korrigieren

**Comment by gizmo2342** [comment]
Kommt mit dem nächsten Update. Hat leider ein bischen gedauert.
