### ISSUE TITLE
Fehlt die Rolle "Nahkämpfer"?

### ISSUE THREAD

**Issue by Raldanash** [gizmo2342/foundryvtt-hexxen1733-system#18]
Ich bin noch frisch bei Hexxen, aber die Rolle Nahkämpfer scheint zu fehlen. (Sorry, hatte mich beim Titel vertan)

**Comment by evilblubb** [comment]
foundryvtt-hexxen1733-system/packs/role.db in Zeile 11 ist er da, muss mir das aktuelle stable ziehen und es mir in foundry anschauen - werd die tage über dazu kommen.

**Comment by gizmo2342** [comment]
> Ich bin noch frisch bei Hexxen, aber die Rolle Nahkämpfer scheint zu fehlen. (Sorry, hatte mich beim Titel vertan)

@Raldanash  Das ist eigenartig. Im Compendium ist er jedenfalls drin und bei mir wird er auch angezeigt. Welche Versionen von Foundry und Hexxen verwendest du? Verwendest du zusätzliche Module?

**Comment by Raldanash** [comment]
Ich hab noch einmal neu importiert und dann kam auch Nahkaempfer rein!

**Comment by gizmo2342** [comment]
Danke für die Rückmeldung.
