### ISSUE TITLE
Bonus/Malus Würfel werden falsch miteinander verrechnet

### ISSUE THREAD

**Issue by Tommycore** [gizmo2342/foundryvtt-hexxen1733-system#19]
**Womit arbeitest du?**
 - OS: WIN 10
 - Browser: (reiche ich nach sobald ich die Info habe)
 - Foundry-Version: 0.7.9
 - HeXXen-Version: 0.6.1
 - weitere Module: Special Dice Roller

**Beschreibung des Fehlers. / Wie kann der Fehler reproduziert werden?**
[Strg] Klick (oder [Shift] Klick) auf Würfelsymbol bei Fertigkeit -> Im Fenster mit +/- Bonus und Maluswürfel auswählen -> Würfeln anklicken. Bei verschiedenen Kombinationen von Bonus und Maluswürfeln wurde die falsche Anzahl Würfel gewürfelt, bzw. im Chatfenster angezeigt. Beispielsweise haben 2 Bonus und 2 Maluswürfel dazu geführt das zwei Zusatzwürfel geworfen wurden, anstatt dass diese sich gegenseitig aufgehoben haben. Der Fehler lässt sich leider NICHT zuverlässig reproduzieren und trat nur anfangs auf.

**Zusätzliche Informationen**
Ich habe gehostet, einen SL-Account für Leander angelegt, und der hat sich damit eingeloggt. OS bezieht sich auf unser beider Betriebssysteme, Browser auf Leander's Browser.

**Comment by gizmo2342** [comment]
Bitte darauf achten, dass sowohl Bonus als auch Malus als positive Zahl angegeben werden müssen.

**Comment by gizmo2342** [comment]
Habe tatsächlich eine Codestelle gefunden, aufgrund der negative Zahlen verworfen werden. Das würde genau zu der Fehlerbeschreibung passen. 

Habe jetzt erstmal dahingehend geändert, dass Vorzeichen ignoriert werden. Später, bei der Überarbeitung des WürfelDialogs werde ich dann die Eingabe negativer Zahlen unterbinden.
