### ISSUE TITLE
Keine installation bei VTT Version 0.7.9

### ISSUE THREAD

**Issue by Stonewall6165** [gizmo2342/foundryvtt-hexxen1733-system#20]
Hallo,

erstmal danke für deine Arbeit.

Ich kann in der aktuellen VTT Version 0.7.9 das Modul nicht installieren.

btw. kannst du deinen mod direkt in VTT hinterlegen?

**Comment by gizmo2342** [comment]
Hallo und Danke.

Wo liegt das Problem?

Du gehst im Foundry Setup auf `Game Systems`, klickst auf `Install System` und kopierst 

`https://github.com/gizmo2342/foundryvtt-hexxen1733-system/raw/stable/system.json`

 unten bei `Manifest-URL` rein. Dann noch `Install` und fertig.

Dass das System noch nicht bei VTT hinterlegt ist, hat seine Gründe. Aber das wird sich diesen Monat voraussichtlich noch ändern.

**Comment by gizmo2342** [comment]
Hauptsache es hat funktioniert.
